name: .NET Core

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build ./MMLib.Ocelot.Provider.AppConfiguration.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./MMLib.Ocelot.Provider.AppConfiguration.sln --configuration Release
