name: Pull Request

on: [pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet build ./MMLib.Ocelot.Provider.AppConfiguration.sln --configuration Release
    - name: Test
      run: dotnet test ./MMLib.Ocelot.Provider.AppConfiguration.sln --configuration Release
